# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filipecn/ClionProjects/Synergy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filipecn/ClionProjects/Synergy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filipecn/ClionProjects/Synergy/CMakeFiles /home/filipecn/ClionProjects/Synergy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filipecn/ClionProjects/Synergy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GlfwExample

# Build rule for target.
GlfwExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GlfwExample
.PHONY : GlfwExample

# fast build rule for target.
GlfwExample/fast:
	$(MAKE) -f CMakeFiles/GlfwExample.dir/build.make CMakeFiles/GlfwExample.dir/build
.PHONY : GlfwExample/fast

#=============================================================================
# Target rules for targets named Synergy

# Build rule for target.
Synergy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Synergy
.PHONY : Synergy

# fast build rule for target.
Synergy/fast:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/build
.PHONY : Synergy/fast

examples/GlfwExample.o: examples/GlfwExample.cpp.o
.PHONY : examples/GlfwExample.o

# target to build an object file
examples/GlfwExample.cpp.o:
	$(MAKE) -f CMakeFiles/GlfwExample.dir/build.make CMakeFiles/GlfwExample.dir/examples/GlfwExample.cpp.o
.PHONY : examples/GlfwExample.cpp.o

examples/GlfwExample.i: examples/GlfwExample.cpp.i
.PHONY : examples/GlfwExample.i

# target to preprocess a source file
examples/GlfwExample.cpp.i:
	$(MAKE) -f CMakeFiles/GlfwExample.dir/build.make CMakeFiles/GlfwExample.dir/examples/GlfwExample.cpp.i
.PHONY : examples/GlfwExample.cpp.i

examples/GlfwExample.s: examples/GlfwExample.cpp.s
.PHONY : examples/GlfwExample.s

# target to generate assembly for a file
examples/GlfwExample.cpp.s:
	$(MAKE) -f CMakeFiles/GlfwExample.dir/build.make CMakeFiles/GlfwExample.dir/examples/GlfwExample.cpp.s
.PHONY : examples/GlfwExample.cpp.s

source/Synergy/Core/ObjFileLoader.o: source/Synergy/Core/ObjFileLoader.cpp.o
.PHONY : source/Synergy/Core/ObjFileLoader.o

# target to build an object file
source/Synergy/Core/ObjFileLoader.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/ObjFileLoader.cpp.o
.PHONY : source/Synergy/Core/ObjFileLoader.cpp.o

source/Synergy/Core/ObjFileLoader.i: source/Synergy/Core/ObjFileLoader.cpp.i
.PHONY : source/Synergy/Core/ObjFileLoader.i

# target to preprocess a source file
source/Synergy/Core/ObjFileLoader.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/ObjFileLoader.cpp.i
.PHONY : source/Synergy/Core/ObjFileLoader.cpp.i

source/Synergy/Core/ObjFileLoader.s: source/Synergy/Core/ObjFileLoader.cpp.s
.PHONY : source/Synergy/Core/ObjFileLoader.s

# target to generate assembly for a file
source/Synergy/Core/ObjFileLoader.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/ObjFileLoader.cpp.s
.PHONY : source/Synergy/Core/ObjFileLoader.cpp.s

source/Synergy/Core/Resources.o: source/Synergy/Core/Resources.cpp.o
.PHONY : source/Synergy/Core/Resources.o

# target to build an object file
source/Synergy/Core/Resources.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/Resources.cpp.o
.PHONY : source/Synergy/Core/Resources.cpp.o

source/Synergy/Core/Resources.i: source/Synergy/Core/Resources.cpp.i
.PHONY : source/Synergy/Core/Resources.i

# target to preprocess a source file
source/Synergy/Core/Resources.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/Resources.cpp.i
.PHONY : source/Synergy/Core/Resources.cpp.i

source/Synergy/Core/Resources.s: source/Synergy/Core/Resources.cpp.s
.PHONY : source/Synergy/Core/Resources.s

# target to generate assembly for a file
source/Synergy/Core/Resources.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Core/Resources.cpp.s
.PHONY : source/Synergy/Core/Resources.cpp.s

source/Synergy/Graphics/Camera.o: source/Synergy/Graphics/Camera.cpp.o
.PHONY : source/Synergy/Graphics/Camera.o

# target to build an object file
source/Synergy/Graphics/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Camera.cpp.o
.PHONY : source/Synergy/Graphics/Camera.cpp.o

source/Synergy/Graphics/Camera.i: source/Synergy/Graphics/Camera.cpp.i
.PHONY : source/Synergy/Graphics/Camera.i

# target to preprocess a source file
source/Synergy/Graphics/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Camera.cpp.i
.PHONY : source/Synergy/Graphics/Camera.cpp.i

source/Synergy/Graphics/Camera.s: source/Synergy/Graphics/Camera.cpp.s
.PHONY : source/Synergy/Graphics/Camera.s

# target to generate assembly for a file
source/Synergy/Graphics/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Camera.cpp.s
.PHONY : source/Synergy/Graphics/Camera.cpp.s

source/Synergy/Graphics/Frustum.o: source/Synergy/Graphics/Frustum.cpp.o
.PHONY : source/Synergy/Graphics/Frustum.o

# target to build an object file
source/Synergy/Graphics/Frustum.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Frustum.cpp.o
.PHONY : source/Synergy/Graphics/Frustum.cpp.o

source/Synergy/Graphics/Frustum.i: source/Synergy/Graphics/Frustum.cpp.i
.PHONY : source/Synergy/Graphics/Frustum.i

# target to preprocess a source file
source/Synergy/Graphics/Frustum.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Frustum.cpp.i
.PHONY : source/Synergy/Graphics/Frustum.cpp.i

source/Synergy/Graphics/Frustum.s: source/Synergy/Graphics/Frustum.cpp.s
.PHONY : source/Synergy/Graphics/Frustum.s

# target to generate assembly for a file
source/Synergy/Graphics/Frustum.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/Frustum.cpp.s
.PHONY : source/Synergy/Graphics/Frustum.cpp.s

source/Synergy/Graphics/GlErrorCheck.o: source/Synergy/Graphics/GlErrorCheck.cpp.o
.PHONY : source/Synergy/Graphics/GlErrorCheck.o

# target to build an object file
source/Synergy/Graphics/GlErrorCheck.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/GlErrorCheck.cpp.o
.PHONY : source/Synergy/Graphics/GlErrorCheck.cpp.o

source/Synergy/Graphics/GlErrorCheck.i: source/Synergy/Graphics/GlErrorCheck.cpp.i
.PHONY : source/Synergy/Graphics/GlErrorCheck.i

# target to preprocess a source file
source/Synergy/Graphics/GlErrorCheck.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/GlErrorCheck.cpp.i
.PHONY : source/Synergy/Graphics/GlErrorCheck.cpp.i

source/Synergy/Graphics/GlErrorCheck.s: source/Synergy/Graphics/GlErrorCheck.cpp.s
.PHONY : source/Synergy/Graphics/GlErrorCheck.s

# target to generate assembly for a file
source/Synergy/Graphics/GlErrorCheck.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/GlErrorCheck.cpp.s
.PHONY : source/Synergy/Graphics/GlErrorCheck.cpp.s

source/Synergy/Graphics/PostProcessor.o: source/Synergy/Graphics/PostProcessor.cpp.o
.PHONY : source/Synergy/Graphics/PostProcessor.o

# target to build an object file
source/Synergy/Graphics/PostProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/PostProcessor.cpp.o
.PHONY : source/Synergy/Graphics/PostProcessor.cpp.o

source/Synergy/Graphics/PostProcessor.i: source/Synergy/Graphics/PostProcessor.cpp.i
.PHONY : source/Synergy/Graphics/PostProcessor.i

# target to preprocess a source file
source/Synergy/Graphics/PostProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/PostProcessor.cpp.i
.PHONY : source/Synergy/Graphics/PostProcessor.cpp.i

source/Synergy/Graphics/PostProcessor.s: source/Synergy/Graphics/PostProcessor.cpp.s
.PHONY : source/Synergy/Graphics/PostProcessor.s

# target to generate assembly for a file
source/Synergy/Graphics/PostProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/PostProcessor.cpp.s
.PHONY : source/Synergy/Graphics/PostProcessor.cpp.s

source/Synergy/Graphics/RenderTarget.o: source/Synergy/Graphics/RenderTarget.cpp.o
.PHONY : source/Synergy/Graphics/RenderTarget.o

# target to build an object file
source/Synergy/Graphics/RenderTarget.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/RenderTarget.cpp.o
.PHONY : source/Synergy/Graphics/RenderTarget.cpp.o

source/Synergy/Graphics/RenderTarget.i: source/Synergy/Graphics/RenderTarget.cpp.i
.PHONY : source/Synergy/Graphics/RenderTarget.i

# target to preprocess a source file
source/Synergy/Graphics/RenderTarget.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/RenderTarget.cpp.i
.PHONY : source/Synergy/Graphics/RenderTarget.cpp.i

source/Synergy/Graphics/RenderTarget.s: source/Synergy/Graphics/RenderTarget.cpp.s
.PHONY : source/Synergy/Graphics/RenderTarget.s

# target to generate assembly for a file
source/Synergy/Graphics/RenderTarget.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/RenderTarget.cpp.s
.PHONY : source/Synergy/Graphics/RenderTarget.cpp.s

source/Synergy/Graphics/ShaderProgram.o: source/Synergy/Graphics/ShaderProgram.cpp.o
.PHONY : source/Synergy/Graphics/ShaderProgram.o

# target to build an object file
source/Synergy/Graphics/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/ShaderProgram.cpp.o
.PHONY : source/Synergy/Graphics/ShaderProgram.cpp.o

source/Synergy/Graphics/ShaderProgram.i: source/Synergy/Graphics/ShaderProgram.cpp.i
.PHONY : source/Synergy/Graphics/ShaderProgram.i

# target to preprocess a source file
source/Synergy/Graphics/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/ShaderProgram.cpp.i
.PHONY : source/Synergy/Graphics/ShaderProgram.cpp.i

source/Synergy/Graphics/ShaderProgram.s: source/Synergy/Graphics/ShaderProgram.cpp.s
.PHONY : source/Synergy/Graphics/ShaderProgram.s

# target to generate assembly for a file
source/Synergy/Graphics/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/Synergy.dir/build.make CMakeFiles/Synergy.dir/source/Synergy/Graphics/ShaderProgram.cpp.s
.PHONY : source/Synergy/Graphics/ShaderProgram.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GlfwExample"
	@echo "... Synergy"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... examples/GlfwExample.o"
	@echo "... examples/GlfwExample.i"
	@echo "... examples/GlfwExample.s"
	@echo "... source/Synergy/Core/ObjFileLoader.o"
	@echo "... source/Synergy/Core/ObjFileLoader.i"
	@echo "... source/Synergy/Core/ObjFileLoader.s"
	@echo "... source/Synergy/Core/Resources.o"
	@echo "... source/Synergy/Core/Resources.i"
	@echo "... source/Synergy/Core/Resources.s"
	@echo "... source/Synergy/Graphics/Camera.o"
	@echo "... source/Synergy/Graphics/Camera.i"
	@echo "... source/Synergy/Graphics/Camera.s"
	@echo "... source/Synergy/Graphics/Frustum.o"
	@echo "... source/Synergy/Graphics/Frustum.i"
	@echo "... source/Synergy/Graphics/Frustum.s"
	@echo "... source/Synergy/Graphics/GlErrorCheck.o"
	@echo "... source/Synergy/Graphics/GlErrorCheck.i"
	@echo "... source/Synergy/Graphics/GlErrorCheck.s"
	@echo "... source/Synergy/Graphics/PostProcessor.o"
	@echo "... source/Synergy/Graphics/PostProcessor.i"
	@echo "... source/Synergy/Graphics/PostProcessor.s"
	@echo "... source/Synergy/Graphics/RenderTarget.o"
	@echo "... source/Synergy/Graphics/RenderTarget.i"
	@echo "... source/Synergy/Graphics/RenderTarget.s"
	@echo "... source/Synergy/Graphics/ShaderProgram.o"
	@echo "... source/Synergy/Graphics/ShaderProgram.i"
	@echo "... source/Synergy/Graphics/ShaderProgram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

